#plugins:
#  - jekyll-include-cache

theme: minima
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

header_pages:
  - members.md
  - projects.md
  - publication.md
  - ack.md
  - joinus.md
  - contact.md

title: RebelsNLU
author: Naoya Inoue
